import { bilingual as b, type FleetState } from './model'

export function createSeed(): FleetState {
  const vehicles: FleetState['vehicles'] = [
    ['BUS 008', 'HRT008', 'Volvo B8R', 'bus', 2022, 'Wollongong', 124820, 3820, 'available'],
    ['BUS 017', 'HRT017', 'Scania K320', 'bus', 2020, 'Wollongong', 218450, 6450, 'maintenance'],
    ['BUS 023', 'HRT023', 'Volvo B8R', 'bus', 2021, 'Shellharbour', 176280, 5110, 'grounded'],
    [
      'BUS 041',
      'HRT041',
      'Mercedes OC 500',
      'bus',
      2023,
      'Wollongong',
      86420,
      2670,
      'awaitingRelease',
    ],
    ['BUS 052', 'HRT052', 'Scania K320', 'bus', 2022, 'Shellharbour', 142100, 4220, 'available'],
    ['BUS 063', 'HRT063', 'Volvo B8R', 'bus', 2024, 'Wollongong', 56780, 1810, 'available'],
    [
      'BUS 076',
      'HRT076',
      'Mercedes OC 500',
      'bus',
      2019,
      'Shellharbour',
      294610,
      8210,
      'available',
    ],
    ['BUS 089', 'HRT089', 'Volvo B8R', 'bus', 2023, 'Wollongong', 98240, 2980, 'available'],
    [
      'CTV 104',
      'HRT104',
      'Toyota HiAce Commuter',
      'community',
      2024,
      'Shellharbour',
      41260,
      1350,
      'available',
    ],
  ].map((v, i) => ({
    id: v[0] as string,
    plate: v[1] as string,
    model: v[2] as string,
    vehicleClass: v[3] as FleetState['vehicles'][number]['vehicleClass'],
    year: v[4] as number,
    depot: v[5] as string,
    mileage: v[6] as number,
    hours: v[7] as number,
    status: v[8] as FleetState['vehicles'][number]['status'],
    vin: `HRTDEMO0000000${String(i + 1).padStart(4, '0')}`,
    active: true,
    telemetryAt: '2026-10-04T20:00:00Z',
  }))
  return {
    version: 2,
    vehicles,
    inspections: [
      {
        id: 'IN-0101',
        vehicleId: 'BUS 023',
        date: '2026-10-01',
        type: 'routine',
        assignee: 'Jamie Chen',
        status: 'pending',
        checks: [],
        note: b('', ''),
      },
      {
        id: 'IN-0102',
        vehicleId: 'BUS 008',
        date: '2026-10-05',
        time: '10:00',
        type: 'routine',
        assignee: 'Jamie Chen',
        status: 'pending',
        checks: [],
        note: b('', ''),
      },
      {
        id: 'IN-0103',
        vehicleId: 'BUS 052',
        date: '2026-10-06',
        type: 'routine',
        assignee: 'Robin Park',
        status: 'pending',
        checks: [],
        note: b('', ''),
      },
      {
        id: 'IN-0104',
        vehicleId: 'BUS 041',
        date: '2026-10-03',
        type: 'reinspection',
        assignee: 'Jamie Chen',
        status: 'passed',
        checks: ['brakes', 'tyres', 'lights', 'doors', 'fluids'].map((key) => ({
          key,
          result: 'pass',
          note: '',
        })),
        note: b(
          'Door sensor tested. All safety checks passed.',
          '车门传感器测试正常，所有安全检查通过。',
        ),
        completedAt: '2026-10-03T04:30:00Z',
      },
      {
        id: 'IN-0105',
        vehicleId: 'BUS 063',
        date: '2026-10-02',
        type: 'routine',
        assignee: 'Jamie Chen',
        status: 'passed',
        checks: ['brakes', 'tyres', 'lights', 'doors', 'fluids'].map((key) => ({
          key,
          result: 'pass',
          note: '',
        })),
        note: b('Routine inspection complete.', '例行检查已完成。'),
        completedAt: '2026-10-02T04:00:00Z',
      },
    ],
    defects: [
      {
        id: 'DF-0021',
        vehicleId: 'BUS 017',
        description: b('Front brake pads below wear limit', '前制动片磨损超过限值'),
        severity: 'critical',
        status: 'processing',
        date: '2026-10-02',
        orderId: 'WO-0042',
      },
      {
        id: 'DF-0022',
        vehicleId: 'BUS 023',
        description: b('Uneven wear on right rear tyre', '右后轮胎异常磨损'),
        severity: 'critical',
        status: 'open',
        date: '2026-10-01',
      },
      {
        id: 'DF-0023',
        vehicleId: 'BUS 052',
        description: b('Interior reading light not working', '车内阅读灯不亮'),
        severity: 'minor',
        status: 'open',
        date: '2026-10-04',
      },
      {
        id: 'DF-0020',
        vehicleId: 'BUS 041',
        description: b('Intermittent door sensor signal', '车门传感器信号不稳定'),
        severity: 'critical',
        status: 'resolved',
        date: '2026-09-30',
        orderId: 'WO-0040',
      },
      {
        id: 'DF-0019',
        vehicleId: 'BUS 052',
        description: b('Rear air-conditioning not cooling', '车厢后部空调不制冷'),
        severity: 'minor',
        status: 'processing',
        date: '2026-10-03',
        orderId: 'WO-0043',
      },
    ],
    orders: [
      {
        id: 'WO-0042',
        vehicleId: 'BUS 017',
        title: b('Replace worn front brake pads', '更换磨损的前制动片'),
        defectIds: ['DF-0021'],
        assignee: 'Sam Taylor',
        status: 'progress',
        date: '2026-10-02',
        note: b('', ''),
        parts: [],
        issued: {},
        labourHours: 0,
        labourRate: 85,
      },
      {
        id: 'WO-0043',
        vehicleId: 'BUS 052',
        title: b('Repair rear air-conditioning unit', '维修车厢后部空调'),
        defectIds: ['DF-0019'],
        assignee: 'Coastline Diesel',
        status: 'assigned',
        date: '2026-10-04',
        note: b('', ''),
        parts: [],
        issued: {},
        labourHours: 0,
        labourRate: 110,
      },
      {
        id: 'WO-0044',
        vehicleId: 'BUS 076',
        title: b('Scheduled oil and filter service', '定期更换机油及滤清器'),
        defectIds: [],
        planId: 'PM-0003',
        assignee: '',
        status: 'pending',
        date: '2026-10-04',
        note: b('', ''),
        parts: [],
        issued: {},
        labourHours: 0,
        labourRate: 85,
      },
      {
        id: 'WO-0040',
        vehicleId: 'BUS 041',
        title: b('Replace and test door sensor', '更换并测试车门传感器'),
        defectIds: ['DF-0020'],
        assignee: 'Casey Wilson',
        status: 'closed',
        date: '2026-09-30',
        note: b(
          'Sensor replaced and calibrated. Functional test passed.',
          '传感器已更换并校准，功能测试通过。',
        ),
        parts: [{ partId: 'PT-0004', quantity: 1, price: 210 }],
        issued: { 'PT-0004': 1 },
        labourHours: 1.5,
        labourRate: 85,
        closedAt: '2026-10-02T05:00:00Z',
        finance: 'financePosted',
        financeRef: 'FIN-2026-0418',
      },
    ],
    parts: [
      {
        id: 'PT-0001',
        name: b('Front brake pad kit', '前制动片套件'),
        sku: 'BRK-102',
        stock: 18,
        minStock: 6,
        price: 150,
        category: b('Braking', '制动系统'),
      },
      {
        id: 'PT-0002',
        name: b('Commercial tyre 295/80', '商用轮胎 295/80'),
        sku: 'TYR-295',
        stock: 4,
        minStock: 5,
        price: 420,
        category: b('Wheels & tyres', '车轮与轮胎'),
      },
      {
        id: 'PT-0003',
        name: b('Engine oil filter', '发动机机油滤清器'),
        sku: 'FLT-204',
        stock: 24,
        minStock: 8,
        price: 38,
        category: b('Engine', '发动机'),
      },
      {
        id: 'PT-0004',
        name: b('Door position sensor', '车门位置传感器'),
        sku: 'SNS-041',
        stock: 3,
        minStock: 4,
        price: 210,
        category: b('Electrical', '电气系统'),
      },
      {
        id: 'PT-0005',
        name: b('LED interior light', '车内 LED 灯'),
        sku: 'LED-012',
        stock: 12,
        minStock: 4,
        price: 24,
        category: b('Electrical', '电气系统'),
      },
      {
        id: 'PT-0006',
        name: b('Engine oil 5L', '发动机机油 5L'),
        sku: 'OIL-005',
        stock: 16,
        minStock: 5,
        price: 65,
        category: b('Engine', '发动机'),
      },
    ],
    plans: [
      {
        id: 'PM-0001',
        vehicleId: 'BUS 008',
        title: b('Routine safety service', '例行安全保养'),
        dueDate: '2026-10-12',
        dueMileage: 130000,
        dueHours: 4000,
        intervalDays: 90,
        intervalMileage: 15000,
        intervalHours: 500,
      },
      {
        id: 'PM-0002',
        vehicleId: 'BUS 052',
        title: b('Engine oil and filter service', '机油及滤清器保养'),
        dueDate: '2026-10-08',
        dueMileage: 145000,
        dueHours: 4500,
        intervalDays: 90,
        intervalMileage: 15000,
        intervalHours: 500,
      },
      {
        id: 'PM-0003',
        vehicleId: 'BUS 076',
        title: b('Engine oil and filter service', '机油及滤清器保养'),
        dueDate: '2026-10-03',
        dueMileage: 290000,
        dueHours: 8000,
        intervalDays: 90,
        intervalMileage: 15000,
        intervalHours: 500,
        orderId: 'WO-0044',
      },
      {
        id: 'PM-0004',
        vehicleId: 'BUS 063',
        title: b('Routine safety service', '例行安全保养'),
        dueDate: '2026-11-15',
        dueMileage: 70000,
        dueHours: 2200,
        intervalDays: 90,
        intervalMileage: 15000,
        intervalHours: 500,
      },
    ],
    audit: [
      {
        id: 'EV-0003',
        at: '2026-10-03T04:30:00Z',
        actor: 'Jamie Chen',
        role: 'inspector',
        entityId: 'IN-0104',
        vehicleId: 'BUS 041',
        message: b('Post-repair inspection passed', '维修后复检通过'),
      },
      {
        id: 'EV-0002',
        at: '2026-10-02T05:00:00Z',
        actor: 'Jordan Lee',
        role: 'reviewer',
        entityId: 'WO-0040',
        vehicleId: 'BUS 041',
        message: b('Repair reviewed and work order closed', '维修审核通过，工单已关闭'),
      },
      {
        id: 'EV-0001',
        at: '2026-10-02T01:00:00Z',
        actor: 'Sam Taylor',
        role: 'technician',
        entityId: 'WO-0042',
        vehicleId: 'BUS 017',
        message: b('Brake pad replacement started', '开始更换制动片'),
      },
    ],
  }
}
